### ISSUE TITLE
RtRetrievalFramework and ReFRACtor

### ISSUE THREAD

**Issue by JinZheeee** [nasa/RtRetrievalFramework#5]
Will this software be updated again?
What's the relationship between RtRetrievalFramework and ReFRACtor?
Is ReFRACtor a better choice?

**Comment by mcduffie** [comment]
[ReFRACtor](https://github.com/refractor) is the follow on to the software in this repository. It is actively being worked on to be a more general purpose Radiative Transfer and Retrieval tool. This software will only be update for OCO-2 specific needs.
