### ISSUE TITLE
CO2 priori file

### ISSUE THREAD

**Issue by JinZheeee** [nasa/RtRetrievalFramework#7]
Hi,
The documentation says that the model needs a priori CO2 profiles, I want to ask where I can download the CO2 file, and how to add the file into the model.

Thanks,
Jin Zhe

**Comment by mcduffie** [comment]
We don't directly use a file for CO2 apriori. We use a model that accounts for seasonal and anthropogenic trends. This is contained in the GasVmrApriori class.

**Comment by JinZheeee** [comment]
OK, thanks. I have another question, also about the apriori value. I have tried to modify the apriori value of the state vector,  but whatever I input, there are two components named Aerosol Shape SO Logarithmic Gaussian for Coefficent 1 and Aerosol Shape OC Logarithmic Gaussian for Coefficent 1, stay unchanged. I want to ask whether the apriori values of these two components are fixed in the model, equal to -5.580156126 and -5.985716421 respectively. And what kinds of aerosols do SO and OC stand for?
