### ISSUE TITLE
Pressure Levels

### ISSUE THREAD

**Issue by JinZheeee** [nasa/RtRetrievalFramework#8]
Hi,
I attempt to change the input data of CO2 apriori and use my own data. I find in the class PressureLevelInput that the input data must be defined on 20 fixed pressure levels (1hPa, 70hPa ,..., 1000hPa, 1050hPa). 
My first question is that sometimes the surface pressure is lower than 1050hPa, for example, 900hPa, is it still necessary to give values of levels higher than 900hPa, and will the values of these levels have a effect on the final results?
My second question is that, in the class Pressure, it says the pressure levels will potentially vary as we do a retrieval, how do they vary?
My third question is that what's the function of class PressureSigma, does the sigma coordinate be used in the retrieval process? And in the pressure section of the result, there are two matrices, named a and b respectively, what do the two matrices represent?
                a:
                20
                 [         0         0         0         0         0         0         0
                          0         0         0         0         0         0         0
                          0         0         0         0         0         0  ]
                b:
                20
                 [    0.0001 0.0526316  0.105263  0.157895  0.210526  0.263158  0.315789
                   0.368421  0.421053  0.473684  0.526316  0.578947  0.631579  0.684211
                   0.736842  0.789474  0.842105  0.894737  0.947368         1  ]

**Comment by mcduffie** [comment]
PressureSigma is what you should use as it allows the surface pressure to change and allows the rest of the pressure levels to adapt. The only thing exposed to the retrieval from it is the surface pressure.

Those two matrices are the sigma level coefficients. There is a constructor for PressureSigma that can create them from a fixed pressure grid.
